name: CI

on:
  push:
    branches: [ test_ci]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List all files
        run: ls

      - name: Install Python
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python Script
        run: python create_file.py

      - name: List all NEW files
        run: ls

# install Python
# Create a new file
# List the files again (prove that python worked)

