name: outputs-demo-2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: unbuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.contents.outputs.data }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run python script
        id: contents
        run: |
          python create_txt_file.py
          contents=$( cat readme.txt )
          echo "::set-output name=data::$contents"
  job2:
    runs-on: unbuntu-latest
    needs: job1
    steps:
      - run: echo "${{needs.job1.outputs.output1}}
  
        
        
